// Client work shown on the homepage slides and the /work page.
// Screenshots live in /public/work/<slug>/ and are produced by the capture + export scripts in
// "~/Documents/Projects/Boostify USA/SEO Tools" (portfolio_capture.mjs, portfolio_mobile.mjs, portfolio_export.mjs).
// portfolio-media.json is generated by the export script; don't hand-edit it.
import media from './portfolio-media.json';

export type Service = 'Web design' | 'Local SEO' | 'Branding' | 'E-commerce' | 'Google Ads' | 'Hosting & care';

export interface PortfolioMedia {
  hero: string;
  heroSm: string;
  full: { src: string; w: number; h: number } | null;
  mobile: string | null;
  /** Colour of the phone page's top edge; tints the frame's status bar. */
  mobileTop?: string;
  inner: { src: string; full: { src: string; w: number; h: number }; path: string; title: string }[];
  /** Full-length phone capture (390px viewport), only for sites shown on /web-design. */
  mobileFull?: { src: string; w: number; h: number } | null;
}

export interface Project {
  slug: string;
  name: string;
  url: string;
  industry: string;
  city?: string;
  services: Service[];
  stack?: string;
  summary: string;
  /** Shown in the homepage slides and the showreel, in this order. */
  featured?: number;
  /** Our build, but the client has since moved to another provider and the live domain shows
   *  someone else's site. Shown from our server copy, never linked. */
  archived?: boolean;
}

const projects: Project[] = [
  { slug: 'blc-custom-homes', featured: 1, name: 'BLC Custom Homes', url: 'https://blccustomhomes.com', industry: 'Custom home builder', city: 'Fresno & Clovis', services: ['Web design', 'Local SEO', 'Hosting & care'], stack: 'Next.js',
    summary: 'Rebuilt a stale WordPress site as a fast static build, kept the old pages ranking with a full 301 map, and run the hosting and technical SEO.' },
  { slug: 'apex-films', featured: 7, name: 'Apex Films', url: 'https://apexfilmsfresno.com', industry: 'Window tint & PPF', city: 'Fresno', services: ['Local SEO', 'Branding', 'Hosting & care'], stack: 'WordPress',
    summary: 'Brand work and local SEO for a Fresno tint and paint protection shop, on a site we host and look after.' },
  { slug: 'copper-crest', featured: 4, name: 'Copper Crest', url: 'https://coppercrest-venue.com', industry: 'Wedding venue', city: 'Washington State', services: ['Web design', 'Hosting & care'], stack: 'Next.js',
    summary: 'One site for two wedding estates under one brand, with a page for each space and the booking inquiry a tap away.' },
  { slug: 'sequoia-air-co', featured: 5, name: 'Sequoia Air Co.', url: 'https://sequoiaairco.com', industry: 'HVAC', city: 'Fresno', services: ['Branding', 'Web design', 'Hosting & care'], stack: 'React',
    summary: 'Renamed Precision Aire to Sequoia Air Co., designed the logo, and relaunched the website under the new name before heat season.' },
  { slug: 'the-hmong-inc', featured: 6, name: 'The Hmong Inc.', url: 'https://thehmonginc.com', industry: 'Non-profit', city: 'Fresno', services: ['Web design', 'Hosting & care'], stack: 'Next.js + Payload',
    summary: 'The site for a Fresno non-profit that supports Southeast Asian small businesses, and home of the Big Fresno Hmong New Year.' },
  { slug: 'green-and-clean', featured: 8, name: 'Green & Clean', url: 'https://greenandcleanlc.com', industry: 'Contractor & landscaping', city: 'Selma', services: ['Web design', 'Local SEO', 'Hosting & care'], stack: 'WordPress',
    summary: 'A new website first, then a monthly local SEO roadmap built around the general contracting side of the business.' },
  { slug: 'triple-c-pressure-washing', featured: 2, name: 'Triple C Pressure Washing', url: 'https://triplecpressurewashing.com', industry: 'Exterior cleaning', city: 'Fresno', services: ['Web design', 'Hosting & care'], stack: 'React',
    summary: 'Website design and build for a family-owned Fresno pressure washing company.' },
  { slug: 'high-throne-rentals', featured: 3, name: 'High Throne Rentals', url: 'https://highthronerentals.com', industry: 'Luxury restroom rentals', city: 'Fresno', services: ['Web design', 'Local SEO', 'Hosting & care'], stack: 'Next.js',
    summary: 'Brought the site back from the Internet Archive when the old one went down, rebuilt it on our hosting, and run local SEO for a Fresno luxury portable restroom rental company.' },
  { slug: 'fresno-management-company', name: 'Fresno Management Company', url: 'https://fresnomanagementcompany.com', industry: 'Property management', city: 'Fresno', services: ['Web design', 'Local SEO', 'Hosting & care'], stack: 'React',
    summary: 'Website and monthly local SEO for a Fresno property manager, with rental listings fed straight from their AppFolio account.' },
  { slug: 'headquarters-window-tint', name: 'Headquarters Window Tint', url: 'https://headquarterswindowtint.com', industry: 'Window tint', city: 'Fresno', services: ['Web design', 'Google Ads', 'Hosting & care'], stack: 'WordPress',
    summary: 'Website design plus the Google Ads that send people to it.' },
  { slug: 'shelby-pools', name: 'Shelby Pools', url: 'https://shelbypoolsllc.com', industry: 'Pool builder', city: 'Clovis', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Website for a Clovis pool builder, hosted and maintained by us.' },
  // Not shown: almond-hulling (Nettra white-label client), fmc-commercial (not our build),
  // full-throttle-suspension (new build not launched yet; add it once it is live on ftskits.com),
  // top-quality-detail, ea-auto-detailing, joaquin-ag-repair (Victor took them off, 2026-09-26).
  // benchmark-pool-supply left out: it is a Shopify store now with no credit to us; confirm it is still our build first.
  { slug: 'martin-energy', name: 'Martin Energy', url: 'https://martinenergyconsultingservices.com', industry: 'Solar & energy', city: 'Fresno', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Full redesign for a Fresno solar energy company, with a page for every service.' },
  { slug: 'fresno-state-today', name: 'Fresno State Today', url: 'https://today.fresnostate.edu', industry: 'University news', city: 'Fresno', services: ['Web design'], stack: 'WordPress',
    summary: 'The WordPress build for Fresno State’s news site, plus training so their staff can publish on it.' },
  { slug: 'ac-pro-roofing', name: 'AC Pro Roofing', url: 'https://acproroofing.com', industry: 'Roofing', city: 'Fresno', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Website for a Fresno roofing contractor, hosted and maintained by us.' },
  { slug: 'barmaids', name: 'Barmaids', url: 'https://barmaids-fresno.com', industry: 'Mobile bar service', city: 'Fresno', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Website for a Fresno mobile bar and bartending service.' },
  { slug: 'deep-feels-therapy', name: 'Deep Feels Therapy', url: 'https://deepfeelstherapy.com', industry: 'Therapy practice', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Website, hosting and upkeep for a therapy practice.' },
  { slug: 'stelas-photography', name: 'Stela’s Photography', url: 'https://stellaseattlephotographer.com', industry: 'Photographer', city: 'Seattle', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Portfolio site for a Seattle photographer.' },
  { slug: 'endo-supersystems', name: 'Endodontic SuperSystems', url: 'https://endosupersystems.com', industry: 'Dental education', services: ['Hosting & care'], stack: 'WordPress',
    summary: 'Hosting and management for an endodontist’s education and product sites.' },
  { slug: 'compass-capital', name: 'Compass Capital', url: 'https://compasscapinvest.com', industry: 'Investment firm', services: ['Web design'], stack: 'WordPress',
    summary: 'Website for an investment firm, handed over to their own hosting account when they asked.' },
  { slug: 'darksigma', name: 'DarkSigma', url: 'https://darksigmalabs.com', industry: 'Technology startup', services: ['Web design'], stack: 'Next.js',
    summary: 'The site for DarkSigma, the technology company Victor runs alongside Boostify.' },
  { slug: 'tcd-tech', name: 'TCD Tech', url: 'https://noemissionstech.com', industry: 'Tesla programming & diagnostics', city: 'Seattle', services: ['Web design'], stack: 'Framer',
    summary: 'Website for a Seattle shop that does Tesla programming, diagnostics and module work.' },
  { slug: 'rfp-rocket', name: 'RFP Rocket', url: 'https://rfprocket.com', industry: 'Software', services: ['Web design', 'Hosting & care'], stack: 'WordPress',
    summary: 'Marketing site for an AI proposal-writing product.' },
  { slug: 'balanced-co', name: 'Balanced Co.', url: 'https://balancedco.llc', industry: 'Industrial materials & piping', city: 'Fresno', services: ['Web design'], stack: 'WordPress', archived: true,
    summary: 'Website for a Fresno industrial contractor: piping, compressed air systems and construction materials, with a page for each.' },
  { slug: 'clean-enterprises', name: 'Clean Enterprises', url: 'https://cleanenterprise.com', industry: 'Equipment & restroom rentals', city: 'Fresno', services: ['Web design'], stack: 'WordPress', archived: true,
    summary: 'Website for a Fresno company that rents luxury restrooms and construction equipment and does commercial cleaning for events and job sites.' },
];

const m = media as Record<string, PortfolioMedia>;
export const portfolio = projects
  .filter(p => m[p.slug])
  .map(p => ({ ...p, media: m[p.slug] }));
export type PortfolioItem = (typeof portfolio)[number];
export const featured = portfolio.filter(p => p.featured).sort((a, b) => (a.featured ?? 0) - (b.featured ?? 0));
export const host = (url: string) => url.replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '');
